version: 2.1
executors:
  dart_sdk_image:
    docker:
      - image: google/dart
  flutter_sdk_image:
    docker:
      - image: cirrusci/flutter:latest

jobs:
  test:
    executor: flutter_sdk_image
    steps:
      - checkout
      - run: tool/ci_test.sh

workflows:
  version: 2.1
  default:
    jobs:
      - test
